### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by FDiskas**
Updated typings to the latest one

### CODE REVIEW

**Comment by abstractFlo** [comment]
Have you tested it? I guess the build process is no more working with shared types :/

**Comment by FDiskas** [comment]
It works. locally it worked without typescript errors. Also `typecript` dev dependency is missing

**Comment by FDiskas** [comment]
Yes - build is failing but the reason is ok
```
Module '"alt-server"' has no exported member 'hash'
Module '"alt-server"' has no exported member 'Vector3'
Property 'destroy' does not exist on type 'Vehicle'. Did you mean 'destroyed'?
Module '"alt-server"' has no exported member 'off'
```
And it is actually right. The code must be updated also. But i'm not a specialist of this boiler plate.

**Comment by abstractFlo** [comment]
We don't update this branch anymore, Atlas 3.1 is nearly done and this Repository would be removed after release.

**Pull request closed without merging**
